[package]
name = "inf319-backend"
version = "0.1.0"
authors = ["Stian Soltvedt <stian@soltvedt.info>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.9"
actix-web = "2.0"
actix-rt = "1.0"
listenfd = "0.3"
dotenv = "0.15"
log = "0.4"
env_logger = "0.7"
serde = "1.0"
serde_json = "1.0"
uuid = { version = "0.8", default-features = false, features = ["serde", "v4"] }
