name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        profile: minimal
        components: "rustfmt,clippy"
        target: x86_64-unknown-linux-gnu
        override: true
    - name: Build
      run: cargo build --verbose
    - name: Run cargo fmt
      run: cargo fmt --all --check
    - name: Run cargo clippy
      run: cargo clippy -D warnings
    - name: Run tests
      run: cargo test --verbose
